Repository aperoMoi/Unsecure, pull requests merged in 2018-10, with the labels that each got.

#11 Add gitignore file
  .gitignore
Labels: Priority: High

#14 create contributing and readme
  CONTRIBUTING.md
  README.md
Labels: Priority: High, administrative content

#18 Added gh-pages theme for documentation
  docs/_config.yml
Labels: Priority: Low

#20 Release v1.0.0
  .gitignore
  CONTRIBUTING.md
  PULL_REQUEST_TEMPLATE.md
  README.md
  docs/_config.yml
Labels: Status: Proposal, administrative content

#21 Add Docker
  app/AppKernel.php
  build/apache2config/000-default.conf
  build/apache2config/apache2.conf
  build/site/Dockerfile
  docker-compose.yml
Labels: Priority: High

#22 Feature/travis ci starting
  .idea/Unsecure.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/php.xml
  .idea/vcs.xml
  .idea/workspace.xml
  .travis.yml
  src/AppBundle/Tests/AdminTest.php
Labels: Priority: High

#23 Script shell to install environment
  .gitignore
  app/config/parameters.yml
  app/logs/dev.log
  start.sh
Labels: Priority: Critical

#24 Gh-pages content
  docs/index.html
Labels: Priority: High

#25 V1.0.1
  .gitignore
  .idea/Unsecure.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/php.xml
  .idea/vcs.xml
  .idea/workspace.xml
  .travis.yml
  app/AppKernel.php
  app/config/parameters.yml
  app/logs/dev.log
  build/apache2config/000-default.conf
  build/apache2config/apache2.conf
  build/site/Dockerfile
  docker-compose.yml
  docs/index.html
  src/AppBundle/Tests/AdminTest.php
  start.sh
Labels: Priority: High, administrative content
